# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcfoverparRcppClean <- function(y_, z_, w_, x_con_, x_mod_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_con_name_, treef_mod_name_, status_interval = 100L, RJ = FALSE, use_mscale = TRUE, use_bscale = TRUE, b_half_normal = TRUE, trt_init = 1.0, verbose_sigma = FALSE, no_output = FALSE) {
    .Call('_bcf_bcfoverparRcppClean', PACKAGE = 'bcf', y_, z_, w_, x_con_, x_mod_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_con_name_, treef_mod_name_, status_interval, RJ, use_mscale, use_bscale, b_half_normal, trt_init, verbose_sigma, no_output)
}

bcfoverparRcppCleanLinear <- function(y_, z_, w_, x_con_, x_mod_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_con_name_, treef_mod_name_, status_interval = 100L, RJ = FALSE, use_mscale = TRUE, use_bscale = TRUE, b_half_normal = TRUE, trt_init = 0.0, verbose_sigma = FALSE, no_output = FALSE, intTreat = TRUE) {
    .Call('_bcf_bcfoverparRcppCleanLinear', PACKAGE = 'bcf', y_, z_, w_, x_con_, x_mod_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_con_name_, treef_mod_name_, status_interval, RJ, use_mscale, use_bscale, b_half_normal, trt_init, verbose_sigma, no_output, intTreat)
}

bcflineartwo <- function(y_, z_, w_, x_con_, x_mod_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_con_name_, treef_mod_name_, status_interval = 100L, RJ = FALSE, use_mscale = TRUE, use_bscale = TRUE, b_half_normal = TRUE, trt_init = 0.0, verbose_sigma = FALSE, no_output = FALSE, tian = FALSE) {
    .Call('_bcf_bcflineartwo', PACKAGE = 'bcf', y_, z_, w_, x_con_, x_mod_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, con_sd, mod_sd, con_alpha, con_beta, mod_alpha, mod_beta, treef_con_name_, treef_mod_name_, status_interval, RJ, use_mscale, use_bscale, b_half_normal, trt_init, verbose_sigma, no_output, tian)
}

sample_beta_j <- function(N, r_beta, z, w_j, tau_j, sigma) {
    .Call('_bcf_sample_beta_j', PACKAGE = 'bcf', N, r_beta, z, w_j, tau_j, sigma)
}

sample_tau_j_slice <- function(tau_old, beta_j, sigma, step_out = 0.5, max_steps = 50L) {
    .Call('_bcf_sample_tau_j_slice', PACKAGE = 'bcf', tau_old, beta_j, sigma, step_out, max_steps)
}

sample_alpha <- function(N, r_alpha, z_, sigma, alpha_prior_sd = 10.0) {
    .Call('_bcf_sample_alpha', PACKAGE = 'bcf', N, r_alpha, z_, sigma, alpha_prior_sd)
}

sample_sigma2_ig <- function(N, resid, shape_prior = 1.0, rate_prior = 0.001) {
    .Call('_bcf_sample_sigma2_ig', PACKAGE = 'bcf', N, resid, shape_prior, rate_prior)
}

